version: 0.2

phases:
  install:
    commands:
      - echo "Installing Yarn..."
      - npm install -g yarn
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yarn install --frozen-lockfile
  build:
    commands:
      - echo "Building Vite application..."
      - yarn build

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
